export const UPDATE_STORIES = 'UPDATE_STORIES';
export const CLEAR_STORIES = 'CLEAR_STORIES';
export const UPDATE_SIGN_UP_NETWORK = 'UPDATE_SIGN_UP_NETWORK';
export const RESET_SIGN_UP_NETWORK = 'RESET_SIGN_UP_NETWORK';
